// https://www.iban.com/country-codes
export const countries = [
  "AR",
  "AU",
  "BE",
  "CL",
  "DE",
  "GB",
  "IN",
  "JP",
  "NO",
  "NZ",
  "RU",
  "US",
  "ZA",
  "AQ",
];

export const nn = {
  "country_of_authority": "Autoritetsland",
  Country: "Land",
  country: "land",
  undefined: "Land manglar",
  AR: "Argentina",
  AU: "Australia",
  AQ: "Antarktis",
  BE: "Belgia",
  CL: "Chile",
  DE: "Tyskland",
  GB: "Storbritannia",
  IN: "India",
  JP: "Japan",
  NO: "Norge",
  NZ: "Ny-Zealand",
  RU: "Russland",
  US: "USA",
  ZA: "Sør-Afrika",
};

export const en = {
  "country_of_authority": "Country of authority",
  Country: "Country",
  country: "country",
  undefined: "Country missing",
  AR: "Argentina",
  AU: "Australia",
  AQ: "Antarctica",
  BE: "Belgium",
  CL: "Chile",
  DE: "Germany",
  GB: "United Kingdom of Great Britain and Northern Ireland",
  IN: "India",
  JP: "Japan",
  NO: "Norway",
  NZ: "New Zealand",
  RU: "Russian Federation",
  US: "United States of America",
  ZA: "South Africa",
};
